export const players = [
  {
    name: 'Ariel',
    picks: ['Michele', 'Tony', 'Tyson', 'Yul'],
    mvp: 'Parvati',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Diane',
    picks: ['Jeremy', 'Parvati', 'Rob', 'Wendell'],
    mvp: 'Sarah',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Fergusson',
    picks: ['Sarah', 'Sophie', 'Tony', 'Tyson'],
    mvp: 'Parvati',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Jen H',
    picks: ['Kim', 'Rob', 'Tyson', 'Yul'],
    mvp: 'Sophie',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Jen W',
    picks: ['Adam', 'Ben', 'Ethan', 'Sarah'],
    mvp: 'Wendell',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Joyce',
    picks: ['Ben', 'Parvati', 'Wendell', 'Yul'],
    mvp: 'Sarah',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Justin B',
    picks: ['Danni', 'Ethan', 'Jeremy', 'Parvati'],
    mvp: 'Yul',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Justin T',
    picks: ['Jeremy', 'Michele', 'Parvati', 'Sarah'],
    mvp: 'Tyson',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Laurie F',
    picks: ['Parvati', 'Sarah', 'Sophie', 'Yul'],
    mvp: 'Ben',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Laurie W',
    picks: ['Danni', 'Jeremy', 'Kim', 'Tyson'],
    mvp: 'Yul',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Lori',
    picks: ['Adam', 'Parvati', 'Sarah', 'Tyson'],
    mvp: 'Wendell',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Mark',
    picks: ['Denise', 'Michele', 'Sarah', 'Tony'],
    mvp: 'Nick',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Mike B',
    picks: ['Michele', 'Nick', 'Sophie', 'Yul'],
    mvp: 'Tyson',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Mike S',
    picks: ['Nick', 'Rob', 'Sarah', 'Yul'],
    mvp: 'Ethan',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Sharon',
    picks: ['Ethan', 'Kim', 'Sarah', 'Sophie'],
    mvp: 'Nick',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
  {
    name: 'Tanner',
    picks: ['Denise', 'Jeremy', 'Nick', 'Rob'],
    mvp: 'Sarah',
    totalScore: 0,
    episodeScores: [0],
    rank: 0,
  },
];
